name: Deploy app on prod
'on':
  push:
    branches:
      - prod
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: SetUp up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      -
        name: Prepare docker-compose
        run: |
              ls -l

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: whatsuplinlin/finalproject-prod:latest

      -
        name: Prepare docker-compose run
        run: |
              mkdir devproject2
              cp docker-compose-prod.yml devproject2/docker-compose.yml
              cd devproject2
              docker-compose -H ${{secrets.HOST_SERVER}} down
              docker-compose -H ${{secrets.HOST_SERVER}} pull
              docker-compose -H ${{secrets.HOST_SERVER}} up -d